"""Add project categories and enhanced project fields

Revision ID: ea8ced3f52e3
Revises: a2574e4d0105
Create Date: 2025-06-17 12:30:49.880725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8ced3f52e3'
down_revision = 'a2574e4d0105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_opensource', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'project_category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('stars')
        batch_op.drop_column('is_opensource')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
